# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
- name: message
  type: string
  default: Install Maven Shaik
  values:
  - Install Maven Shaik
  - Install Maven for Windows
  - Install Maven for Linux
  - Install Maven for Mac



trigger:
- master

pool: Sample

steps:
- task: Maven@3
  displayName: ${{ parameters.message }}
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
